apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    name: guestbook-service
    app: demo-guestbook-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    # Name of Pod Label
    name: guestbook-pod
    # Name of application running within the Pod
    app: demo-guestbook-app